name: linter

concurrency:
  group: linter-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4', '8.5']
        dependency: [lowest, highest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl
          ini-values: date.timezone=Europe/Zurich,memory_limit=-1,session.gc_probability=0,zend.assertions=1
          coverage: none
          tools: composer

      - name: PHP version
        run: php -v

      - name: Composer Validate
        run: composer validate --no-check-publish --strict

      - name: Composer Install Dependencies (highest)
        if: matrix.dependency == 'highest'
        run: composer update --prefer-dist --no-progress --no-scripts --no-interaction

      - name: Composer Install Dependencies (lowest)
        if: matrix.dependency == 'lowest'
        run: composer update --prefer-lowest --prefer-dist --no-progress --no-scripts --no-interaction

      - name: PHPUnit Run
        run: composer phpunit

      - name: Composer Tools PHPCS Install Dependencies
        if: matrix.php-version == '8.5' && matrix.dependency == 'highest'
        run: composer update --working-dir tools/php-cs-fixer --prefer-dist --no-progress --no-scripts --no-interaction

      - name: PHPCS Run
        if: matrix.php-version == '8.5' && matrix.dependency == 'highest'
        run: composer phpcs

      - name: Composer Tools PHPSTAN Install Dependencies
        if: matrix.php-version == '8.5' && matrix.dependency == 'highest'
        run: composer update --working-dir tools/phpstan --prefer-dist --no-progress --no-scripts --no-interaction

      - name: PHPSTAN Run
        if: matrix.php-version == '8.5' && matrix.dependency == 'highest'
        run: composer phpstan
